# Generated by Django 6.0.2 on 2026-02-13 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_content', models.TextField()),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(default='python', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('BUG', 'Bug'), ('SECURITY', 'Security'), ('STYLE', 'Style'), ('PERFORMANCE', 'Performance'), ('COMPLEXITY', 'Complexity'), ('OTHER', 'Other')], max_length=50)),
                ('message', models.TextField()),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20)),
                ('suggestion', models.TextField(blank=True, null=True)),
                ('review_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='reviewer.reviewrequest')),
            ],
        ),
    ]
